#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cups-pk-helper
Version  : 0.2.7
Release  : 9
URL      : https://www.freedesktop.org/software/cups-pk-helper/releases/cups-pk-helper-0.2.7.tar.xz
Source0  : https://www.freedesktop.org/software/cups-pk-helper/releases/cups-pk-helper-0.2.7.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: cups-pk-helper-data = %{version}-%{release}
Requires: cups-pk-helper-libexec = %{version}-%{release}
Requires: cups-pk-helper-license = %{version}-%{release}
Requires: cups-pk-helper-locales = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : cups-dev
BuildRequires : glib-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : polkit-dev

%description
cups-pk-helper
==============
http://www.freedesktop.org/wiki/Software/cups-pk-helper

%package data
Summary: data components for the cups-pk-helper package.
Group: Data

%description data
data components for the cups-pk-helper package.


%package libexec
Summary: libexec components for the cups-pk-helper package.
Group: Default
Requires: cups-pk-helper-license = %{version}-%{release}

%description libexec
libexec components for the cups-pk-helper package.


%package license
Summary: license components for the cups-pk-helper package.
Group: Default

%description license
license components for the cups-pk-helper package.


%package locales
Summary: locales components for the cups-pk-helper package.
Group: Default

%description locales
locales components for the cups-pk-helper package.


%prep
%setup -q -n cups-pk-helper-0.2.7
cd %{_builddir}/cups-pk-helper-0.2.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664819296
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/cups-pk-helper
cp %{_builddir}/cups-pk-helper-%{version}/COPYING %{buildroot}/usr/share/package-licenses/cups-pk-helper/4cc77b90af91e615a64ae04893fdffa7939db84c
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang cups-pk-helper

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/org.opensuse.CupsPkHelper.Mechanism.service
/usr/share/dbus-1/system.d/org.opensuse.CupsPkHelper.Mechanism.conf
/usr/share/polkit-1/actions/org.opensuse.cupspkhelper.mechanism.policy

%files libexec
%defattr(-,root,root,-)
/usr/libexec/cups-pk-helper-mechanism

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cups-pk-helper/4cc77b90af91e615a64ae04893fdffa7939db84c

%files locales -f cups-pk-helper.lang
%defattr(-,root,root,-)

